# SUBDOMAIN ENUMERATION ONLY - COMMAND REFERENCE (MULTI-DOMAIN)

## 1. PASSIVE DISCOVERY
# Passive domain discovery without DNS resolution (Amass)
amass enum -passive -df dml.txt -o amass_passive.txt

## 2. CERTIFICATE TRANSPARENCY LOGS

# Query crt.sh for certificates containing multiple domains
while read dm; do curl -s "https://crt.sh/?q=%25.$dm&output=json" | jq -r '.[].name_value' | sed 's/\*\.//g'; done < dml.txt | sort -u > crtsh.txt

# Batch certificate search via CertSpotter API
while read dm; do curl -s "https://api.certspotter.com/v1/issuances?domain=$dm&include_subdomains=true&expand=dns_names" | jq -r '.[].dns_names[]' | sed 's/\"//g'; done < dml.txt | sort -u > certspotter.txt

# Extract subdomains from TLS certificates of discovered hosts
tlsx --input-file discovered_subs.txt --output-file tls_sub_dml.txt


## 3. WEB ARCHIVES & HISTORICAL DATA

# Extract subdomains from Wayback Machine URLs for multiple domains
while read dm; do waybackurls "$dm" | grep -oE "[a-zA-Z0-9._-]+\.$dm"; done < dml.txt | sort -u > wayback_subs.txt

# Alternative Wayback data extraction using GAU for multiple domains
while read dm; do gau "$dm" | grep -oE "[a-zA-Z0-9._-]+\.$dm"; done < dml.txt | sort -u > gau_subs.txt

# Query CommonCrawl dataset for historical subdomains
while read dm; do cc.py "$dm"; done < dml.txt | sort -u > commoncrawl_subs.txt

# Extract subdomains from URLScan.io scan results
while read dm; do curl -s "https://urlscan.io/api/v1/search/?q=domain:$dm" | jq -r '.results[].page.domain'; done < dml.txt | sort -u > urlscan_subs.txt


## 4. SECURITY PLATFORM APIS

# SecurityTrails API subdomain enumeration for multiple domains
while read dm; do curl -s "https://api.securitytrails.com/v1/domain/$dm/subdomains" -H "APIKEY: YOUR_KEY" | jq -r '.subdomains[]' | awk "{print \$0\".$dm\"}"; done < dml.txt > securitytrails.txt

# AlienVault OTX threat intelligence search for multiple domains
while read dm; do otx -s "$dm" -e; done < dml.txt | sort -u > alienvault_subs.txt

# Censys certificate search for multiple domains
while read dm; do censys search "443.https.tls.certificate.parsed.names: $dm" | jq -r .; done < dml.txt | sort -u > censys_subs.txt

# Shodan host search for multiple domains
while read dm; do shodan domain "$dm"; done < dml.txt | sort -u > shodan_subs.txt


## 5. DNS BRUTEFORCING

# DNS bruteforcing with wildcard detection using PureDNS for multiple domains
while read dm; do puredns bruteforce wordlist.txt "$dm" -r resolvers.txt -w puredns_temp.txt; cat puredns_temp.txt >> puredns_output.txt; done < dml.txt

# Fast DNS resolution and bruteforcing with DNSx for multiple domains
dnsx -dL dml.txt -w wordlist.txt -o dnsx_brute.txt

# DNS enumeration using Gobuster for multiple domains
while read dm; do gobuster dns -d "$dm" -w wordlist.txt -o gobuster_temp.txt; cat gobuster_temp.txt >> gobuster_dns.txt; done < dml.txt

# DNS bruteforcing with Nmap scripting engine for multiple domains
while read dm; do nmap --script dns-brute "$dm" -oA "nmap_dns_$dm"; done < dml.txt


## 6. PERMUTATION & ALTERNATIVE NAMES

# Generate permutations of discovered subdomains using AltDNS
altdns -i discovered_subs.txt -o altdns_patterns.txt -w permutation_words.txt

# Resolve DNS permutations generated by AltDNS
cat altdns_patterns.txt | dnsx -silent -a -resp -o altdns_resolved.txt

# Generate domain permutations using DNSGen for discovered subdomains
dnsgen discovered_subs.txt | tee dnsgen_output.txt

# Regulator for advanced subdomain permutation
while read dm; do regulator -t "$dm" -f discovered_subs.txt -o "regulator_$dm.txt"; done < dml.txt


## 7. VIRTUAL HOST DISCOVERY

# Discover virtual hosts via HTTP Host header bruteforcing for multiple domains
while read dm; do ffuf -u http://$dm -H "Host: FUZZ.$dm" -w wordlist.txt -o "vhosts_$dm.json"; done < dml.txt

# VHost discovery filtering error responses
while read dm; do ffuf -u http://$dm -H "Host: FUZZ.$dm" -w wordlist.txt -fc 400,404 -o "vhosts_filtered_$dm.json"; done < dml.txt

# Virtual host enumeration with Gobuster for multiple domains
while read dm; do gobuster vhost -u http://$dm -w wordlist.txt -o "vhost_results_$dm.txt"; done < dml.txt


## 8. DATA AGGREGATION & PROCESSING

# Merge all discovery files and remove duplicates
cat *.txt | sort -u | anew all_combined_subs.txt

# Filter for valid subdomain patterns for all domains
while read dm; do cat all_subs.txt | grep -E "^[a-zA-Z0-9][a-zA-Z0-9.-]*\.$dm$"; done < dml.txt > valid_subs.txt

# Count total unique subdomains discovered per domain
while read dm; do echo "$dm: $(grep -c "$dm$" all_combined_subs.txt)"; done < dml.txt > counts.txt

# Remove wildcard domain patterns from results
cat all_subs.txt | grep -v "^\*\." > non_wildcard_subs.txt

# Extract unique root domains from discovered subdomains
cat all_subs.txt | grep -oE '[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$' | sort -u > root_dml.txt


## 9. AUTOMATION PIPELINES

# One-liner comprehensive passive enumeration for multiple domains
while read dm; do subfinder -d "$dm" | assetfinder --subs-only "$dm" | anew subs.txt && curl -s "https://crt.sh/?q=%25.$dm&output=json" | jq -r '.[].name_value' | sed 's/\*\.//g' | anew subs.txt; done < dml.txt

# Complete pipeline: passive + certificates + bruteforce for multiple domains
while read dm; do subfinder -d "$dm" -silent | anew all_subs.txt && chaos -d "$dm" -silent | anew all_subs.txt && curl -s "https://crt.sh/?q=%25.$dm&output=json" | jq -r '.[].name_value' | sed 's/\*\.//g' | anew all_subs.txt && dnsx -d "$dm" -w wordlist.txt -silent | anew all_subs.txt; done < dml.txt

# Simple monitoring for new subdomains across multiple domains
while read dm; do old="${domain}_old.txt"; new="${domain}_new.txt"; subfinder -d "$dm" -o "$new"; if [ -f "$old" ]; then comm -13 <(sort "$old") <(sort "$new") > "new_${domain}.txt"; fi; mv "$new" "$old"; done < dml.txt


## 10. SPECIALIZED ENUMERATION

# Search GitHub for target-related subdomains and secrets across domains
git-hound --subdomain-file existing_subs.txt --config config.yaml

# Hunter.io email search to find associated domains
while read dm; do curl -s "https://api.hunter.io/v2/domain-search?domain=$dm&api_key=KEY" | jq -r '.data.emails[].value' | cut -d'@' -f2; done < dml.txt | sort -u > email_dml.txt

# Search for AWS infrastructure related to multiple domains
while read dm; do aws s3 ls | grep -i "$dm" | cut -d' ' -f3; done < dml.txt > aws_subs.txt

# Check for Azure subdomains across multiple domains
while read dm; do host -t CNAME *."$dm" | grep azure | cut -d' ' -f1 | sed 's/\.$//'; done < dml.txt > azure_subs.txt


## 11. CONTINUOUS MONITORING SETUP

# Multi-domain diff-based monitoring script
#!/bin/bash
DOMAINS_FILE="dml.txt"

while read dm; do
    OLD_FILE="previous_$dm.txt"
    NEW_FILE="current_$dm.txt"
    
    # Run enumeration
    subfinder -d $dm -silent > $NEW_FILE
    chaos -d $dm -silent >> $NEW_FILE
    
    # Find new subdomains
    if [ -f $OLD_FILE ]; then
        diff $OLD_FILE $NEW_FILE | grep "^>" | cut -c3- > "new_$dm.txt"
    fi
    
    # Update tracking file
    mv $NEW_FILE $OLD_FILE
done < $dml_FILE

# Crontab entry for hourly monitoring of multiple domains
# 0 * * * * /path/to/monitor_multi.sh


## 12. OUTPUT FORMATTING

# Convert results to JSON format grouped by domain
while read dm; do grep "$dm$" discovered_subs.txt | jq -R -s "{domain: \"$dm\", subdomains: split(\"\n\") | map(select(. != \"\"))}"; done < dml.txt > subdomains_by_domain.json

# Create comprehensive text report with timestamp and per-domain breakdown
echo "# Multi-Domain Subdomain Enumeration Results" > report.txt
echo "# Date: $(date)" >> report.txt
echo "# Domains Processed: $(wc -l dml.txt | cut -d' ' -f1)" >> report.txt
echo "" >> report.txt

while read dm; do
    count=$(grep -c "$dm$" discovered_subs.txt)
    echo "## $dm - $count subdomains" >> report.txt
    grep "$dm$" discovered_subs.txt | sort | sed 's/^/- /' >> report.txt
    echo "" >> report.txt
done < dml.txt

# Generate sorted unique list with domain categorization
while read dm; do
    echo "# $dm" >> categorized_subs.txt
    grep "$dm$" discovered_subs.txt | sort -u | nl -w2 -s'. ' >> categorized_subs.txt
    echo "" >> categorized_subs.txt
done < dml.txt
